[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
allow_untyped_defs = true
allow_incomplete_defs = true
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false
warn_return_any = false

[[tool.mypy.overrides]]
module = ["torch.*", "transformers.*"]
ignore_missing_imports = true
