# 主配置文件，聚合各子配置
include:
  - ai_api.yaml
  - memory.yaml
  - rag.yaml
  - mcp.yaml
  - plugins.yaml
  # 其他如 tools.yaml

# 项目配置文件
system:
  name: 'Synapse AI'
  version: '1.0.0'
  debug: false
  log_level: 'INFO'
  log_path: 'logs' # 日志路径
  port: 2333 # 服务端口

api:
  version: 'v1'
  rate_limit: '10/minute' # 限制每分钟10次请求
  allowed_origins:
    - 'http://localhost:8080' 
    - 'http://localhost:3000'
  api_key: 'L3cev1ABEb0YAtIsJcJVrRVQEKzvax4nQrWhqq9RjmU' # 已迁移自 ai_api.yaml
