# 主配置文件，聚合各子配置
include:
  - ai_api.yaml
  - memory.yaml
  - rag.yaml
  - mcp.yaml
  - plugins.yaml
  # 其他如 tools.yaml

# 项目配置文件
system:
  name: 'Synapse' # 项目名称
  version: '0.1.0' # 项目版本
  debug: true # 是否开启调试模式
  log_level: 'INFO' # 日志级别
  log_path: 'logs' # 日志路径
  port: 2333 # 服务端口
